[package]
name = "cadence"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cadence"
path = "src/bin/main.rs"

[lib]
name = "cadence"
path = "src/lib.rs"

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = [
  "font-kit",
  "wayland",
] }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "49229371e095bfd2ca77d336b5972b16956f0a87" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "49229371e095bfd2ca77d336b5972b16956f0a87" }
chrono = "0.4.45"
uuid = { version = "1.24.1", features = ["serde", "v7"] }
jiff = { version = "0.2.35", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.145"
async-channel = "2.5.0"
rusqlite = { version = "0.40.2", features = ["bundled"] }

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", features = ["test-support"] }
tempfile = "3.23.0"
