[package]
name = "cadence-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cadence-core.workspace = true
gpui.workspace = true
gpui-component.workspace = true
jiff.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
serde_json.workspace = true
uuid.workspace = true
